config/routes.rb
Rails.application.routes.draw do

  resources :members

  resources :visitor
  root 'visitors#index'
 

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.js
        format.html
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :email)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

	def index
		@member = Member.new

		respond_to do |format|
			format.html
			format.js
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebSite</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/Front Views/about.html.erb
<h1>About Stuff</h1>

app/views/main/Front Views/contact.html.erb
<h1>Contact Stuff</h1>

app/views/main/Front Views/events.html.erb
<h1>Events Stuff (Calendar and Media)</h1>

app/views/main/Front Views/home.html.erb
<h1>Welcome Stuff</h1>

app/views/main/Front Views/mailinglist.html.erb
<h1>Mailing List Stuff</h1>

app/views/main/index.html.erb
<html>

<head>
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>
</head>

<body>

	<div id="top_box">
		<td>
			<%= image_tag("logo.jpg", class: 'logo') %>
		</td>
	</div>

	<div id="pad">
		<ul id="nav_bar">
			<li class="button" id="home"><span>Home</span></li>
    		<li class="button" id="about"><span>About Us</span></li>
    		<li class="button" id="events"><span>Events</span></li>
    		<li class="button" id="contact"><span>Contact Us</span></li>
    		<li class="button" id="mailing_list"><span>Mailing List</span></li>
		</ul>
	</div>

	<div id="info_box">
	</div>

</body>
</html>

app/views/members/_form.html.erb
<h3>Join our e-mail list!</h3>
<%= form_for(@member, remote: true, id: "email_form") do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.email %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'members/form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @member.email %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/visitors/_about.html.erb
<h1>About Us Stuff</h1>

app/views/visitors/_contact.html.erb
<h1>Contact Us Stuff</h1>

app/views/visitors/_email.html.erb
<h1>Email List Stuff</h1>

app/views/visitors/_events.html.erb
<h1>Events Stuff</h1>

app/views/visitors/_home.html.erb
<h1>Welcome Stuff</h1>

app/views/visitors/index.html.erb
<html>

<head>

	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag "application" %>

</head>

<body>

	<div id="top_bar">
		<ul id="social_links">
			<li class="social_link"><%= link_to image_tag("facebook.jpg"), "http://www.facebook.com", title: "ACTION Facebook" %></li>
			<li class="social_link"><%= link_to image_tag("twitter.jpg"), "http://www.twitter.com", title: "ACTION Twitter" %></li>
			<li class="social_link"><%= link_to image_tag("instagram.jpg"), "http://www.instagram.com", title: "ACTION Instagram" %></li>
		</ul>
	</div>

	<div id="top_box">
		<td>
			<%= image_tag("logo.jpg", class: 'logo') %>
		</td>

		<div>
		</div>
	</div>

	<div id="pad">
		<ul id="nav_bar">
			<!-- This is necessary because inline-block is whitespace dependent -->
			<%= link_to "<span>Home</span>".html_safe, root_path, id: "home", class: "button", remote: true %><%= link_to "<span>About Us</span>".html_safe, root_path, id: "about", class: "button", remote: true %><%= link_to "<span>Events</span>".html_safe, root_path, id: "events", class: "button", remote: true %><%= link_to "<span>Contact Us</span>".html_safe, root_path, id: "contact", class: "button", remote: true %><%= link_to "<span>E-mail List</span>".html_safe, root_path, id: "email", class: "button", remote: true %>
		</ul>
	</div>

	<div id="info_box">
		<div class="selected-i">
			<%= render 'home' %>
		</div>
		<div id="home-i" class="hidden">
			<%= render 'home' %>
		</div>
		<div id="about-i" class="hidden">
			<%= render 'about' %>
		</div>
		<div id="events-i" class="hidden">
		<%= render 'events' %>
		</div>
		<div id="contact-i" class="hidden">
			<%= render 'contact' %>
		</div>
		<div id="email-i" class="hidden">
			<%= render "members/form" %>
		</div>
		<div id="thanks" class="hidden">
			<h1>Thanks!</h1>
		</div>
	</div>

</body>
</html>